import CaldrLogo from "@assets/caldr_logo.png";
import { IconMoon, IconSun } from "@tabler/icons-react";
import { Link } from "react-router";
import { useCaldrStore } from "../../stores";
import styles from "./styles.module.scss";

export default function ModuleLayout({ children, moduleName, moduleDescription, className }: ModuleLayoutProps) {
	const { toggleTheme, theme } = useCaldrStore();

	return (
		<div className={styles.moduleLayout}>
			<header>
				<img src={CaldrLogo} alt="Caldr Logo" />
				<h1>{moduleName}</h1>
				<h2>{moduleDescription}</h2>
				<span className={styles.spacer}></span>
				<button onClick={toggleTheme}>
					{theme === "light" && <IconSun />}
					{theme === "dark" && <IconMoon />}
				</button>
			</header>
			<nav>
				<Link to="/">← Return to Menu</Link>
			</nav>
			<main {...{ className }}>
				{children}
			</main>
			<footer>
				<p>
					This tool is intended for reference use only.
					All calculations and outputs generated by Caldr must be independently reviewed and verified by a licensed engineer or the engineer of record (EOR).
					Caldr assumes no responsibility for the accuracy, completeness, or applicability of its outputs in final designs or construction documents.
				</p>
			</footer>
		</div>
	);
}

interface ModuleLayoutProps extends React.PropsWithChildren<{}> {
	moduleName: string;
	moduleDescription: string;
	className?: string;
}
