import { useCaldrStore } from "@stores/index";
import { IconBrandGithub, IconFileSettings, IconMoon, IconPrinter, IconSun } from "@tabler/icons-react";
import { Helmet } from "react-helmet-async";
import { Link, useLocation, useNavigate } from "react-router";

import WorkInProgress from "./WorkInProgress";

export default function ModuleLayout({ children, moduleName, moduleDescription, className }: ModuleLayoutProps) {
	const { toggleTheme, theme, printPage } = useCaldrStore();

	const navigate = useNavigate();
	const location = useLocation();

	return (
		<div>
			<Helmet>
				<title>{moduleName} | Caldr</title>
				<meta name="description" content={moduleDescription} />
			</Helmet>

			<header
				className="primary-container"
				style={{ position: "sticky", top: 0, zIndex: 2 }}>
				<nav>
					<button
						onClick={() => navigate(-1)}
						className="circle transparent">
						<i>arrow_back</i>
						<div className="tooltip bottom">Back</div>
					</button>
					<Link to="/">
						<img
							src={theme === "light" ? "/caldr_logo.png" : "/caldr_logo_dark.png"}
							alt="Caldr Logo"
							height="50px" />
					</Link>
					<h6>{moduleName}</h6>
					<span className="max">{moduleDescription}</span>
					<button
						className="circle transparent"
						onClick={() => navigate("/project_settings")}
						disabled={location?.pathname === "/project_settings"}>
						<IconFileSettings />
						<div className="tooltip bottom">Project Settings</div>
					</button>
					<button
						className="circle transparent"
						onClick={printPage}>
						<IconPrinter />
						<div className="tooltip bottom">Print Page</div>
					</button>
					<button
						className="circle transparent"
						onClick={toggleTheme}
						title="Toggle Theme">
						{theme === "light" && <IconMoon />}
						{theme === "dark" && <IconSun />}
						<div className="tooltip bottom">Toggle Theme</div>
					</button>
					<Link
						to="https://github.com/CaldrPro/caldr/tree/master"
						target="_blank">
						<button className="circle transparent">
							<IconBrandGithub />
							<div className="tooltip bottom">Source Code</div>
						</button>
					</Link>
				</nav>
			</header>
			<main
				{...{ className }}
				style={{ overflow: "initial" }}>
				{children ?? <WorkInProgress />}
			</main>
			<footer>
				<p>
					This tool is intended for reference use only.
					All calculations and outputs generated by Caldr must be independently reviewed and verified by a licensed engineer or the engineer of record (EOR).
					Caldr assumes no responsibility for the accuracy, completeness, or applicability of its outputs in final designs or construction documents.
				</p>
			</footer>
		</div>
	);
}

interface ModuleLayoutProps extends React.PropsWithChildren<{}> {
	moduleName: string;
	moduleDescription: string;
	className?: string;
}
